/**
 * Seed Data — Demo Products
 * ────────────────────────────────────────────────────────────────────────────
 * These are demo products for development/preview only.
 * Replace with real MongoDB data before launch.
 * 
 * All product images reference /assets/products/{slug}/ folders.
 * Seed 8 realistic products across all categories.
 */

export const seedProducts = [
  {
    id: 'prod-001',
    name: 'Ivory Bloom Crochet Dress',
    slug: 'ivory-bloom-crochet-dress',
    description:
      'A delicate, hand-crocheted dress in warm ivory, designed for little ones who deserve something truly special. Each bloom motif is lovingly stitched by hand — no two pieces are identical.',
    price: 2499,
    comparePrice: 2999,
    images: [
      '/assets/products/ivory-bloom-crochet-dress/1.jpg',
      '/assets/products/ivory-bloom-crochet-dress/2.jpg',
      '/assets/products/ivory-bloom-crochet-dress/3.jpg',
    ],
    category: 'crochet',
    subcategory: 'dresses',
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y'],
    colors: [
      { name: 'Ivory',    hex: '#FAF7F2' },
      { name: 'Blush',    hex: '#E8C4B8' },
      { name: 'Cream',    hex: '#F5EFE4' },
    ],
    material: '100% cotton yarn, soft-spun for sensitive skin',
    care: 'Hand wash cold · Lay flat to dry · Do not bleach',
    featured: true,
    newArrival: true,
    customizable: true,
    stock: 8,
    badge: 'New Arrival',
    tags: ['crochet', 'dress', 'ivory', 'handmade'],
  },
  {
    id: 'prod-002',
    name: 'Sandy Smock Kidswear Set',
    slug: 'sandy-smock-kidswear-set',
    description:
      'A beautifully smocked two-piece set in warm sand tones. Soft, breathable, and made for little personalities to shine. Comes with a matching hair bow.',
    price: 1899,
    comparePrice: null,
    images: [
      '/assets/products/sandy-smock-kidswear-set/1.jpg',
      '/assets/products/sandy-smock-kidswear-set/2.jpg',
    ],
    category: 'kidswear',
    subcategory: 'sets',
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y'],
    colors: [
      { name: 'Sand',     hex: '#D4C4B0' },
      { name: 'Oatmeal',  hex: '#E8DDD0' },
    ],
    material: 'Premium cotton fabric with hand-smocking',
    care: 'Machine wash gentle · Warm iron if needed',
    featured: true,
    newArrival: false,
    customizable: true,
    stock: 12,
    badge: null,
    tags: ['kidswear', 'smock', 'set', 'handmade'],
  },
  {
    id: 'prod-003',
    name: 'Blush Petal Baby Romper',
    slug: 'blush-petal-baby-romper',
    description:
      'A soft, petal-detailed crochet romper for little ones. Gentle on sensitive skin, gentle on the eyes.',
    price: 1599,
    comparePrice: 1899,
    images: [
      '/assets/products/blush-petal-baby-romper/1.jpg',
      '/assets/products/blush-petal-baby-romper/2.jpg',
      '/assets/products/blush-petal-baby-romper/3.jpg',
    ],
    category: 'crochet',
    subcategory: 'rompers',
    sizes: ['1Y', '2Y', '3Y', '4Y'],
    colors: [
      { name: 'Blush',  hex: '#E8C4B8' },
      { name: 'Ivory',  hex: '#FAF7F2' },
    ],
    material: 'Organic cotton yarn, hypoallergenic',
    care: 'Hand wash cold · Lay flat to dry',
    featured: true,
    newArrival: true,
    customizable: false,
    stock: 5,
    badge: 'Bestseller',
    tags: ['crochet', 'romper', 'gift'],
  },
  {
    id: 'prod-004',
    name: 'Sage Garden Crochet Top',
    slug: 'sage-garden-crochet-top',
    description:
      'A lightweight crochet top in muted sage, perfect for layering on warm days. Features a delicate open-stitch pattern across the back.',
    price: 1299,
    comparePrice: null,
    images: [
      '/assets/products/sage-garden-crochet-top/1.jpg',
      '/assets/products/sage-garden-crochet-top/2.jpg',
    ],
    category: 'crochet',
    subcategory: 'tops',
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y'],
    colors: [
      { name: 'Sage',     hex: '#B8C4B0' },
      { name: 'Oatmeal',  hex: '#E8DDD0' },
    ],
    material: 'Cotton-linen blend yarn',
    care: 'Hand wash cold · Air dry',
    featured: false,
    newArrival: false,
    customizable: true,
    stock: 15,
    badge: null,
    tags: ['crochet', 'top', 'sage', 'summer'],
  },
  {
    id: 'prod-005',
    name: 'Warm Brown Birthday Frock',
    slug: 'warm-brown-birthday-frock',
    description:
      'A show-stopping birthday frock in warm brown and ivory, with layered crochet skirt and a satin sash. Made to order — designed to be remembered.',
    price: 3499,
    comparePrice: null,
    images: [
      '/assets/products/warm-brown-birthday-frock/1.jpg',
      '/assets/products/warm-brown-birthday-frock/2.jpg',
      '/assets/products/warm-brown-birthday-frock/3.jpg',
      '/assets/products/warm-brown-birthday-frock/4.jpg',
    ],
    category: 'kidswear',
    subcategory: 'occasion',
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y'],
    colors: [
      { name: 'Warm Brown', hex: '#6B4F3A' },
      { name: 'Ivory',      hex: '#FAF7F2' },
    ],
    material: 'Crochet cotton top with layered tulle/satin base skirt',
    care: 'Dry clean recommended · Store in garment bag',
    featured: true,
    newArrival: true,
    customizable: true,
    stock: 3,
    badge: 'Made to Order',
    tags: ['occasion', 'birthday', 'frock', 'custom', 'crochet'],
  },
  {
    id: 'prod-006',
    name: 'Oatmeal Sibling Matching Set',
    slug: 'oatmeal-sibling-matching-set',
    description:
      'A coordinated set for brothers and sisters — because little moments are sweeter when shared. Available in mixed sizing for different-aged siblings.',
    price: 3199,
    comparePrice: 3799,
    images: [
      '/assets/products/oatmeal-sibling-matching-set/1.jpg',
      '/assets/products/oatmeal-sibling-matching-set/2.jpg',
    ],
    category: 'kidswear',
    subcategory: 'sets',
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y'],
    colors: [
      { name: 'Oatmeal',  hex: '#E8DDD0' },
      { name: 'Cream',    hex: '#F5EFE4' },
    ],
    material: 'Soft cotton, hand-finished details',
    care: 'Machine wash gentle · Cool iron',
    featured: false,
    newArrival: false,
    customizable: true,
    stock: 7,
    badge: 'Popular',
    tags: ['sibling', 'matching', 'set', 'kidswear'],
  },
  {
    id: 'prod-007',
    name: 'Cream Lace Crochet Dress',
    slug: 'cream-lace-crochet-dress',
    description:
      'An heirloom-quality crochet dress with a fine lace pattern, made for christenings, naming ceremonies, and first portraits.',
    price: 2899,
    comparePrice: null,
    images: [
      '/assets/products/cream-lace-crochet-dress/1.jpg',
      '/assets/products/cream-lace-crochet-dress/2.jpg',
    ],
    category: 'crochet',
    subcategory: 'occasion',
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y'],
    colors: [
      { name: 'Cream',  hex: '#F5EFE4' },
      { name: 'Ivory',  hex: '#FAF7F2' },
      { name: 'White',  hex: '#FFFFFF' },
    ],
    material: 'Fine cotton yarn, hand-knotted lace detail',
    care: 'Hand wash cold · Dry flat · Do not wring',
    featured: false,
    newArrival: false,
    customizable: true,
    stock: 4,
    badge: null,
    tags: ['crochet', 'lace', 'christening', 'occasion', 'heirloom'],
  },
  {
    id: 'prod-008',
    name: 'Sand & Blush Photoshoot Set',
    slug: 'sand-blush-photoshoot-set',
    description:
      'Designed for milestone photography sessions. A coordinated crochet and fabric set that photographs beautifully in natural light.',
    price: 2199,
    comparePrice: 2499,
    images: [
      '/assets/products/sand-blush-photoshoot-set/1.jpg',
      '/assets/products/sand-blush-photoshoot-set/2.jpg',
      '/assets/products/sand-blush-photoshoot-set/3.jpg',
    ],
    category: 'crochet',
    subcategory: 'photoshoot',
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y'],
    colors: [
      { name: 'Sand',   hex: '#D4C4B0' },
      { name: 'Blush',  hex: '#E8C4B8' },
    ],
    material: 'Mixed: crochet cotton + soft muslin fabric',
    care: 'Hand wash cold · Air dry',
    featured: false,
    newArrival: true,
    customizable: false,
    stock: 6,
    badge: 'New Arrival',
    tags: ['photoshoot', 'baby', 'milestone', 'crochet', 'set'],
  },
];

export const seedCategories = [
  { id: 'cat-all',            name: 'All',                    slug: 'all'            },
  { id: 'cat-crochet',        name: 'Crochet',                slug: 'crochet'        },
  { id: 'cat-kids-dresses',   name: 'Kids Dresses',           slug: 'kids-dresses'   },
  { id: 'cat-kids-crochet',   name: 'Kids Crochet',           slug: 'kids-crochet'   },
  { id: 'cat-floral-crochet', name: 'Floral Crochet',         slug: 'floral-crochet' },
  { id: 'cat-gifts',          name: 'Handmade Gifts',         slug: 'gifts'          },
  { id: 'cat-new',            name: 'New Arrivals',           slug: 'new-arrivals'   },
  { id: 'cat-custom',         name: 'Custom',                 slug: 'custom'         },
];

export default seedProducts;
